import { item } from "./catalog-item.js";

export const antiPatterns = [
  item("Generic SaaS gradients", "digital", "clean"),
  item("Excessive rounded cards", "digital", "soft"),
  item("Stock photography", "editorial", "clean"),
  item("Decorative clutter", "maximal", "dense"),
  item("Low-contrast body text", "soft", "minimal"),
  item("Tiny primary actions", "minimal", "sparse"),
  item("Unstructured spacing", "playful", "maximal"),
  item("Too many font families", "editorial", "maximal"),
  item("Meaningless glass effects", "digital", "soft"),
  item("Gratuitous animation", "digital", "playful"),
  item("Inconsistent icon styles", "digital", "playful"),
  item("Mobile-hostile fixed widths", "digital", "dense"),
  item("Long unreadable line lengths", "editorial", "dense"),
  item("Hidden navigation", "digital", "minimal"),
  item("Overloaded hero copy", "editorial", "dense"),
  item("Repetitive card grids", "digital", "dense"),
  item("Random shadows", "digital", "soft"),
  item("Fake dashboard metrics", "digital", "dense"),
  item("Ambiguous button labels", "digital", "serious"),
  item("Visual effects that reduce readability", "digital", "maximal"),
  item("Purple-blue AI gradients", "digital", "soft"),
  item("Floating glass cards everywhere", "digital", "soft"),
  item("Decorative orbs without purpose", "futuristic", "soft"),
  item("Fake 3D blobs", "digital", "soft"),
  item("Unusable novelty typography", "playful", "maximal"),
  item("Hero-only design with no product proof", "editorial", "sparse"),
  item("Over-rounded SaaS cards", "digital", "soft"),
  item("Dark dashboard with neon noise", "digital", "dark"),
  item("Decorative hero that hides the product", "editorial", "maximal"),
  item("Placeholder UI with fake content", "digital", "clean"),
  item("Effects applied to every surface", "digital", "maximal"),
  item("Mobile layout that only stacks blindly", "digital", "dense"),
] as const;
