import { item } from "./catalog-item.js";

export const eras = [
  item("Ancient Egypt", "historic", "warm", "textured"),
  item("Classical Greece", "historic", "clean", "serious"),
  item("Roman Empire", "historic", "serious", "warm"),
  item("Medieval", "historic", "dark", "textured"),
  item("Gothic", "historic", "dark", "sharp"),
  item("Renaissance", "historic", "editorial", "warm"),
  item("Baroque", "historic", "luxury", "maximal"),
  item("Rococo", "historic", "luxury", "playful", "soft"),
  item("Victorian", "historic", "textured", "serious"),
  item("Belle Epoque", "historic", "luxury", "warm"),
  item("Art Nouveau", "historic", "organic", "soft"),
  item("Art Deco", "historic", "luxury", "sharp"),
  item("Bauhaus", "historic", "clean", "minimal"),
  item("Mid-century modern", "retro", "clean", "warm"),
  item("Space Age", "retro", "futuristic", "playful"),
  item("Soviet modernism", "historic", "industrial", "serious"),
  item("1970s retro", "retro", "warm", "textured"),
  item("1980s synthwave", "retro", "digital", "bright"),
  item("1990s cyberculture", "retro", "digital", "underground"),
  item("Y2K", "retro", "digital", "playful"),
  item("Contemporary", "clean", "editorial"),
  item("Near future", "futuristic", "digital", "clean"),
  item("Far future", "futuristic", "digital", "sharp"),
  item("Post-apocalyptic future", "futuristic", "dark", "textured"),
  item("Early internet", "retro", "digital", "playful"),
  item("Web 1.0", "retro", "digital", "clean"),
  item("Windows 95", "retro", "digital", "playful"),
  item("Arcade", "retro", "digital", "bright"),
  item("8-bit console", "retro", "digital", "playful"),
  item("16-bit console", "retro", "digital", "playful"),
  item("Retro terminal", "retro", "digital", "dark"),
  item("Dot-com futurism", "retro", "futuristic", "digital"),
  item("Frutiger Aero", "retro", "digital", "bright"),
  item("Vaporwave", "retro", "digital", "playful"),
  item("Cyberpunk", "futuristic", "digital", "dark", "underground"),
  item("Solarpunk", "futuristic", "organic", "bright"),
  item("Biopunk", "futuristic", "organic", "dark"),
  item("Cassette futurism", "retro", "futuristic", "industrial"),
  item("Retro futurism", "retro", "futuristic", "playful"),
  item("Ancient alien civilization", "historic", "futuristic", "textured"),
  item("Dark fantasy kingdom", "historic", "dark", "textured"),
  item("Industrial dystopia", "industrial", "futuristic", "dark"),
  item("Corporate utopia", "futuristic", "clean", "bright"),
  item("Space colony", "futuristic", "industrial", "clean"),
  item("Neon megacity", "futuristic", "digital", "bright", "dark"),
  item("Analog sci-fi laboratory", "retro", "futuristic", "industrial"),
  item("Interstellar civilization", "futuristic", "digital", "luxury"),
  item("Post-human minimalism", "futuristic", "minimal", "cold"),
] as const;
