import { item } from "./catalog-item.js";

export const layouts = [
  item("Strict Swiss grid", "editorial", "clean"),
  item("Asymmetric editorial grid", "editorial", "sharp"),
  item("Modular card grid", "digital", "clean"),
  item("Product-forward hero with next section visible", "maximal", "editorial"),
  item("Split pane with persistent detail area", "sharp", "clean"),
  item("Layered collage", "editorial", "textured", "maximal"),
  item("Single-column narrative", "editorial", "sparse"),
  item("Mixed-scale utility grid", "digital", "clean"),
  item("Masonry grid", "digital", "dense"),
  item("Horizontal scroll narrative", "digital", "editorial"),
  item("Full-bleed sections", "maximal", "editorial"),
  item("Poster composition", "editorial", "sharp"),
  item("Task-first dashboard workspace", "digital", "dense"),
  item("Sidebar workspace with inspector panel", "digital", "serious"),
  item("Centered monument", "minimal", "serious"),
  item("Staggered blocks", "editorial", "playful"),
  item("Diagonal flow", "sharp", "playful"),
  item("Timeline", "editorial", "clean"),
  item("Catalog grid", "editorial", "dense"),
  item("Technical schematic", "industrial", "digital"),
  item("Command-center split pane", "digital", "dense"),
  item("Dense table-first workspace", "digital", "dense"),
  item("Product demo viewport", "digital", "clean"),
  item("Comparison matrix", "editorial", "dense"),
  item("Documentation split pane", "digital", "editorial"),
  item("Map and list hybrid", "digital", "dense"),
  item("Kanban with detail drawer", "digital", "dense"),
] as const;
