import { item } from "./catalog-item.js";

export const palettes = [
  item("Charcoal and acid green", "dark", "bright", "industrial"),
  item("Black and electric cyan", "dark", "bright", "digital"),
  item("Deep navy and neon magenta", "dark", "bright", "digital"),
  item("Warm ivory and oxblood", "warm", "luxury", "historic"),
  item("Concrete gray and safety orange", "industrial", "bright"),
  item("Paper white and ink black", "clean", "editorial"),
  item("Muted earth tones", "organic", "warm", "soft"),
  item("Forest green and cream", "organic", "warm"),
  item("Terracotta and sand", "organic", "warm", "soft"),
  item("Dusty rose and burgundy", "warm", "soft", "luxury"),
  item("Pastel candy colors", "bright", "playful", "soft"),
  item("Ice blue and silver", "cold", "clean"),
  item("Chrome and ultraviolet", "futuristic", "bright", "cold"),
  item("Cobalt and lemon", "bright", "playful"),
  item("Emerald and gold", "luxury", "warm"),
  item("Midnight blue and copper", "dark", "warm", "luxury"),
  item("Black and red", "dark", "sharp"),
  item("Sepia and faded teal", "retro", "textured"),
  item("CRT green monochrome", "retro", "digital", "dark"),
  item("Amber terminal monochrome", "retro", "digital", "warm"),
  item("Grayscale", "clean", "serious"),
  item("High-key white monochrome", "bright", "clean", "minimal"),
  item("Low-key black monochrome", "dark", "minimal"),
  item("Solarized dark", "digital", "dark"),
  item("Vaporwave pink and cyan", "retro", "digital", "playful"),
  item("Synthwave purple and orange", "retro", "digital", "bright"),
  item("Frutiger sky blue and grass green", "retro", "bright", "organic"),
  item("Bauhaus primary colors", "historic", "bright", "sharp"),
  item("Art Deco black and champagne", "historic", "luxury", "dark"),
  item("Victorian jewel tones", "historic", "luxury", "dark"),
  item("Industrial rust and steel", "industrial", "textured"),
  item("Holographic rainbow", "futuristic", "bright", "playful"),
  item("Bioluminescent aqua", "futuristic", "organic", "bright"),
  item("Toxic lime and purple", "bright", "underground"),
  item("Soft lavender and slate", "soft", "cold"),
  item("Coral and turquoise", "bright", "warm", "playful"),
  item("Chocolate and mint", "warm", "playful"),
  item("Ultramarine and hot pink", "bright", "sharp"),
  item("Mustard and petrol blue", "retro", "warm"),
  item("Pearl white and graphite", "clean", "luxury"),
  item("Desert sunset gradient", "warm", "organic"),
  item("Arctic blue gradient", "cold", "clean"),
  item("Neon city night", "digital", "dark", "bright"),
  item("Moss and stone", "organic", "textured"),
  item("Burnt orange and charcoal", "warm", "dark"),
] as const;
