import { item } from "./catalog-item.js";

export const signatureDetails = [
  item("Subtle CRT scanline texture", "digital", "retro", "textured"),
  item("Giant section numbers", "editorial", "sharp"),
  item("Sticker clusters", "playful", "maximal"),
  item("Blueprint measurement marks", "industrial", "digital"),
  item("Pixel icons", "digital", "retro"),
  item("Terminal cursor", "digital", "retro"),
  item("Marquee ticker", "editorial", "retro"),
  item("Cropped corner brackets", "digital", "sharp"),
  item("Ornamental dividers", "historic", "luxury"),
  item("Single reflective 3D accent object", "futuristic", "luxury"),
  item("Holographic highlights", "futuristic", "bright"),
  item("Torn-paper collage edge", "editorial", "textured"),
  item("Handwritten annotations", "organic", "playful"),
  item("Dense footnotes", "editorial", "dense"),
  item("Oversized quotation marks", "editorial", "maximal"),
  item("Functional annotation arrows", "industrial", "digital"),
  item("Warning labels", "industrial", "sharp"),
  item("Barcode motifs", "industrial", "digital"),
  item("Windowed desktop panels", "digital", "retro"),
  item("Circular navigation marker", "digital", "clean"),
  item("Tabular status strips", "digital", "dense"),
  item("Inline measurement ticks", "industrial", "digital"),
  item("Section stamps", "editorial", "serious"),
  item("Inspectable callouts", "digital", "clean"),
  item("Micro charts in headers", "digital", "dense"),
  item("Keyboard-command badges", "digital", "clean"),
  item("Layered annotations", "editorial", "dense"),
  item("Stateful empty screens", "digital", "clean"),
] as const;
