import { item } from "./catalog-item.js";

export const styles = [
  item("Minimalism", "minimal", "clean", "sparse"),
  item("Brutalism", "industrial", "sharp", "serious"),
  item("Neo-brutalism", "industrial", "sharp", "playful"),
  item("Swiss design", "editorial", "clean", "minimal"),
  item("International typographic style", "editorial", "clean", "serious"),
  item("Editorial", "editorial", "clean"),
  item("Magazine collage", "editorial", "maximal", "textured"),
  item("Maximalism", "maximal", "dense", "playful"),
  item("Glassmorphism", "digital", "soft", "clean"),
  item("Neumorphism", "digital", "soft", "minimal"),
  item("Flat design", "digital", "clean", "minimal"),
  item("Material-inspired", "digital", "clean"),
  item("Geometric abstraction", "sharp", "clean", "editorial"),
  item("Organic modernism", "organic", "soft", "clean"),
  item("Luxury editorial", "luxury", "editorial", "serious"),
  item("Corporate modernism", "clean", "serious", "minimal"),
  item("Utilitarian", "industrial", "clean", "serious"),
  item("Industrial", "industrial", "textured", "serious"),
  item("Blueprint", "industrial", "digital", "clean"),
  item("Technical manual", "industrial", "editorial", "serious"),
  item("Constructivism", "historic", "sharp", "serious"),
  item("De Stijl", "historic", "sharp", "clean"),
  item("Memphis", "retro", "playful", "bright"),
  item("Psychedelic", "retro", "playful", "maximal"),
  item("Grunge", "underground", "textured", "dark"),
  item("Punk zine", "underground", "editorial", "textured"),
  item("Streetwear", "underground", "editorial", "sharp"),
  item("Graffiti-inspired", "underground", "playful", "textured"),
  item("Retro futurism", "retro", "futuristic", "playful"),
  item("Sci-fi interface", "futuristic", "digital", "clean"),
  item("Cybernetic", "futuristic", "digital", "industrial"),
  item("Terminal UI", "digital", "retro", "dark"),
  item("Pixel art", "digital", "retro", "playful"),
  item("Vaporwave", "digital", "retro", "playful"),
  item("Synthwave", "digital", "retro", "bright"),
  item("Frutiger Aero", "digital", "retro", "bright"),
  item("Dark academia", "historic", "dark", "editorial"),
  item("Cottagecore", "organic", "soft", "warm"),
  item("Museum archive", "historic", "editorial", "serious"),
  item("High-fashion campaign", "luxury", "editorial", "sharp"),
  item("Monochrome photography", "editorial", "serious", "clean"),
  item("Pop art", "historic", "playful", "bright"),
  item("Comic-book", "editorial", "playful", "bright"),
  item("Handcrafted", "organic", "textured", "warm"),
  item("Experimental web", "digital", "playful", "underground"),
] as const;
