import { item } from "./catalog-item.js";

export const typography = [
  item("Geometric sans", "clean", "sharp"),
  item("Condensed grotesk", "editorial", "sharp"),
  item("Humanist sans", "clean", "soft"),
  item("Neo-grotesk", "clean", "editorial"),
  item("Wide grotesk", "sharp", "editorial"),
  item("Rounded sans", "soft", "playful"),
  item("Monospace terminal", "digital", "retro"),
  item("Monospace technical", "digital", "industrial"),
  item("Slab serif", "editorial", "serious"),
  item("Editorial serif", "editorial", "luxury"),
  item("High-contrast Didone", "luxury", "editorial", "sharp"),
  item("Old-style serif", "historic", "warm"),
  item("Transitional serif", "historic", "editorial"),
  item("Blackletter accent", "historic", "dark"),
  item("Art Nouveau display", "historic", "organic"),
  item("Art Deco display", "historic", "luxury", "sharp"),
  item("Bauhaus geometric display", "historic", "sharp", "clean"),
  item("Pixel bitmap", "digital", "retro", "playful"),
  item("CRT raster", "digital", "retro", "textured"),
  item("Stencil", "industrial", "sharp"),
  item("Industrial signage", "industrial", "serious"),
  item("Typewriter", "retro", "editorial", "textured"),
  item("Newspaper headline", "editorial", "serious"),
  item("Magazine display", "editorial", "maximal"),
  item("Fashion editorial", "luxury", "editorial"),
  item("Handwritten marker", "organic", "playful"),
  item("Brush lettering", "organic", "textured"),
  item("Graffiti display", "underground", "textured"),
  item("Comic lettering", "playful", "editorial"),
  item("Sci-fi extended", "futuristic", "digital"),
  item("Cyberpunk condensed", "futuristic", "digital", "sharp"),
  item("Mechanical engraved", "industrial", "textured"),
  item("Architectural lettering", "industrial", "clean"),
  item("Blueprint annotation", "industrial", "digital"),
  item("Retro computer", "retro", "digital"),
  item("Y2K techno", "retro", "digital", "playful"),
  item("Psychedelic warped", "retro", "playful", "maximal"),
  item("Minimal lowercase", "minimal", "clean"),
  item("All-caps utilitarian", "industrial", "serious"),
  item("Mixed serif and monospace", "editorial", "digital"),
  item("Mixed grotesk and display", "editorial", "maximal"),
  item("Oversized numerals", "editorial", "sharp"),
  item("Tiny annotation text", "dense", "industrial"),
  item("Variable-width experimental", "digital", "playful"),
  item("Cutout collage lettering", "textured", "editorial", "playful"),
] as const;
